import { MainSchema } from "@/db/db.schema";
import { uuid, text, numeric, timestamp } from "drizzle-orm/pg-core";

/**
 * Delivery Orders Table (Outbound)
 * 
 * @description Document issued by SME upon goods delivery to ES's branch.
 * Each Delivery Order is created from a Transfer Order and represents
 * the actual delivery execution. No partial deliveries, splits, or backorders.
 * 
 * @field doNo - Unique Delivery Order number generated by SME
 * @field toId - Reference to the source Transfer Order (one-to-one)
 * 
 * @status
 * - CREATED: DO created, ready for picking
 * - PICKING: Items being picked from warehouse
 * - PACKED: Items packed and ready for dispatch
 * - READY_FOR_COLLECTION: Ready for transporter to collect
 * - COLLECTED: Picked up by transporter
 * - DELIVERED_PENDING_PROOF: Delivered but awaiting signed proof
 * - DELIVERED_CONFIRMED: Delivery confirmed with signed proof
 * - CANCELLED: Delivery Order cancelled
 */
export const DeliveryOrdersTable = MainSchema.table('delivery_orders', {
  id: uuid('id').defaultRandom().notNull().primaryKey(),
  doNo: text('delivery_order_no').unique().notNull(),
  poNo: text('purchase_order_no').unique().notNull(),

  status: text('status').notNull().default('CREATED'),

  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  createdBy: text('created_by').notNull(),
  updatedBy: text('updated_by'),
});

/**
 * Delivery Order Items Table
 * 
 * @description Line items for each Delivery Order.
 * Tracks the required, picked, and packed quantities for each SKU.
 * 
 * @field doId - Reference to the parent Delivery Order
 * @field skuId - Reference to the SKU being delivered
 * @field qtyRequired - Quantity required (from Transfer Order)
 * @field qtyPicked - Quantity actually picked from warehouse
 * @field qtyPacked - Quantity packed for delivery
 */
export const DeliveryOrderItemsTable = MainSchema.table('delivery_order_items', {
  id: uuid('id').defaultRandom().notNull().primaryKey(),
  purchaseOrderNo: text('purchase_order_no').notNull(),
  skuId: uuid('sku_id').notNull(),
  qtyRequired: numeric('qty_required', { precision: 10, scale: 2 }).notNull(),
  qtyPicked: numeric('qty_picked', { precision: 10, scale: 2 }).default('0'),
  qtyPacked: numeric('qty_packed', { precision: 10, scale: 2 }).default('0'),

  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  createdBy: text('created_by').notNull(),
  updatedBy: text('updated_by'),
});

export type DeliveryOrderType = typeof DeliveryOrdersTable.$inferSelect;
export type DeliveryOrderInsertType = typeof DeliveryOrdersTable.$inferInsert;
export type DeliveryOrderFilter = {
  id?: string | string[];
  doNo?: string;
  toId?: string | string[];
  status?: string | string[];
  createdBy?: string | string[];
  createdAtFrom?: string;
  createdAtTo?: string;
};

export type DeliveryOrderItemType = typeof DeliveryOrderItemsTable.$inferSelect;
export type DeliveryOrderItemInsertType = typeof DeliveryOrderItemsTable.$inferInsert;
export type DeliveryOrderItemFilter = {
  id?: string | string[];
  doId?: string | string[];
  skuId?: string | string[];
};
