import { MainSchema } from "@/db/db.schema";
import { uuid, text, numeric, timestamp } from "drizzle-orm/pg-core";

/**
 * Goods Received Notes (GRN) Table
 * 
 * @description Document issued by SME and sent to NetSuite after receiving goods from a supplier.
 * The GRN serves as official acknowledgment of goods receipt and is used for inventory
 * and accounting reconciliation.
 * 
 * @field grnNo - Unique GRN reference number generated by SME
 * @field supplierId - Reference to the supplier who delivered the goods
 * @field supplierDeliveryId - Reference to the associated supplier delivery
 * @field poNo - Purchase Order number for cross-reference
 * 
 * @status
 * - DRAFT: GRN created but not yet finalized
 * - SUBMITTED: GRN submitted for approval
 * - APPROVED: GRN approved by authorized personnel
 * - SENT: GRN sent to NetSuite
 * - FAILED: GRN transmission to NetSuite failed
 */
export const GrnsTable = MainSchema.table('grns', {
  id: uuid('id').defaultRandom().notNull().primaryKey(),
  grnNo: text('grn_no').unique().notNull(),
  supplierId: uuid('supplier_id').notNull(),
  supplierDeliveryId: uuid('supplier_delivery_id'),
  poNo: text('po_no'),

  status: text('status').notNull().default('DRAFT'),
  receivedAt: timestamp('received_at'),

  approvedBy: uuid('approved_by'),
  approvedAt: timestamp('approved_at'),

  notes: text('notes'),
  proofUrl: text('proof_url'),
  warehouseId: uuid('warehouse_id'),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
});

export type GrnType = typeof GrnsTable.$inferSelect;
export type GrnInsertType = typeof GrnsTable.$inferInsert;

/**
 * GRN Items Table
 * 
 * @description Line items for each Goods Received Note.
 * Each record represents a specific SKU received as part of a GRN.
 * 
 * @field grnId - Reference to the parent GRN
 * @field skuId - Reference to the SKU received
 * @field qty - Quantity received
 * @field remarks - Additional notes or comments
 */
export const GrnItemsTable = MainSchema.table('grn_items', {
  id: uuid('id').defaultRandom().notNull().primaryKey(),
  grnId: uuid('grn_id').notNull(),
  skuId: uuid('sku_id').notNull(),
  qty: numeric('qty', { precision: 10, scale: 2 }).notNull(),
  lossQty: numeric('loss_qty', { precision: 10, scale: 2 }).notNull().default('0'),
  remarks: text('remarks'),
  rackId: uuid('rack_id'),
  /**
   * Optional expiry date for this GRN item.
   * Multiple GRN items may exist for the same SKU with different expiry dates.
   */
  expiryDate: timestamp('expiry_date'),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
});

/**
 * GRN Item Racks Join Table
 *
 * @description Maps GRN items to one or more racks.
 * A single GRN item can be associated with multiple rack locations.
 */
export const GrnItemRacksTable = MainSchema.table('grn_item_racks', {
  id: uuid('id').defaultRandom().notNull().primaryKey(),
  grnItemId: uuid('grn_item_id').notNull(),
  rackId: uuid('rack_id').notNull(),
});

export type GrnItemRackType = typeof GrnItemRacksTable.$inferSelect;
export type GrnItemRackInsertType = typeof GrnItemRacksTable.$inferInsert;
