import { MainSchema } from "@/db/db.schema";
import { uuid, text, numeric, timestamp, boolean, jsonb } from "drizzle-orm/pg-core";
import { OrganizationsTable } from "@/features/master-data/organization.model";
import { EsAdvanceNoticesTable } from "@/features/es/es.model";

/**
 * Goods Received Notes (GRN) Table
 * 
 * @description Document issued by SME and sent to NetSuite after receiving goods from a supplier.
 * The GRN serves as official acknowledgment of goods receipt and is used for inventory
 * and accounting reconciliation.
 * 
 * @field grnNo - Unique GRN reference number generated by SME
 * @field supplierId - Reference to the supplier who delivered the goods
 * @field supplierDeliveryId - Reference to the associated supplier delivery
 * @field poNo - Purchase Order number for cross-reference
 * 
 * @status
 * - DRAFT: GRN created but not yet finalized
 * - SUBMITTED: GRN submitted for approval
 * - APPROVED: GRN approved by authorized personnel
 * - SENT: GRN sent to NetSuite
 * - FAILED: GRN transmission to NetSuite failed
 */
export const GrnsTable = MainSchema.table('grns', {
  id: uuid('id').defaultRandom().notNull().primaryKey(),
  organizationId: uuid('organization_id').notNull().references(() => OrganizationsTable.organizationId),
  grnNo: text('grn_no').unique().notNull(),
  supplierId: uuid('supplier_id').notNull(),
  supplierDeliveryId: uuid('supplier_delivery_id'),
  poNo: text('po_no'),

  status: text('status').notNull().default('DRAFT'),
  receivedAt: timestamp('received_at'),

  approvedBy: uuid('approved_by'),
  approvedAt: timestamp('approved_at'),

  notes: text('notes'),
  proofUrl: text('proof_url'),
  warehouseId: uuid('warehouse_id'),

  /**
   * Links this GRN to the ES advance notice it was created from.
   * NULL if created manually (no prior ASN from NetSuite).
   */
  advanceNoticeId: uuid('advance_notice_id').references(() => EsAdvanceNoticesTable.id),

  endUserId: uuid('end_user_id'),

  nsError: jsonb('ns_error'),
  nsSentAt: timestamp('ns_sent_at', { withTimezone: true }),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
});

export type GrnType = typeof GrnsTable.$inferSelect;
export type GrnInsertType = typeof GrnsTable.$inferInsert;

/**
 * GRN Items Table
 * 
 * @description Line items for each Goods Received Note.
 * Each record represents a specific SKU received as part of a GRN.
 * 
 * @field grnId - Reference to the parent GRN
 * @field skuId - Reference to the SKU received
 * @field qty - Quantity received
 * @field remarks - Additional notes or comments
 */
export const GrnItemsTable = MainSchema.table('grn_items', {
  id: uuid('id').defaultRandom().notNull().primaryKey(),
  grnId: uuid('grn_id').notNull(),
  skuId: uuid('sku_id').notNull(),
  qty: numeric('qty', { precision: 10, scale: 2 }).notNull(),
  lossQty: numeric('loss_qty', { precision: 10, scale: 2 }).notNull().default('0'),
  lossRackId: uuid('loss_rack_id'),
  remarks: text('remarks'),
  rackId: uuid('rack_id'),
  /**
   * Optional expiry date for this GRN item.
   * Multiple GRN items may exist for the same SKU with different expiry dates.
   */
  expiryDate: timestamp('expiry_date'),
  /**
   * Lot number assigned by the supplier or manufacturer to identify this production batch.
   * Used for traceability, recall management, and FEFO/FIFO/LIFO picking.
   */
  lotNo: text('lot_no'),
  /**
   * Priority flag — when true, this batch is sorted to the top of the pick list
   * ahead of other batches for the same SKU (regardless of FIFO/LIFO/FEFO).
   * If ALL batches for a SKU are flagged, the flags cancel out and base strategy applies.
   */
  priorityFlag: boolean('priority_flag').notNull().default(false),

  /**
   * Snapshot of qty still owed against the linked PO/ASN at the moment this
   * GRN was submitted for approval. NULL when not linked to a PO/ASN, or
   * when this item predates the feature. Never recomputed after submission.
   */
  remainingCtn: numeric('remaining_ctn', { precision: 10, scale: 2 }),
  remainingLoosePcs: numeric('remaining_loose_pcs', { precision: 10, scale: 2 }),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by'),
});

/**
 * GRN Item Racks Join Table
 *
 * @description Maps GRN items to one or more racks.
 * A single GRN item can be associated with multiple rack locations.
 */
export const GrnItemRacksTable = MainSchema.table('grn_item_racks', {
  id: uuid('id').defaultRandom().notNull().primaryKey(),
  grnItemId: uuid('grn_item_id').notNull(),
  rackId: uuid('rack_id').notNull(),
  quantity: numeric('quantity', { precision: 10, scale: 2 }).notNull().default('0'),
});

export type GrnItemRackType = typeof GrnItemRacksTable.$inferSelect;
export type GrnItemRackInsertType = typeof GrnItemRacksTable.$inferInsert;

/**
 * GRN Item Loss Racks Join Table
 *
 * @description Maps GRN items to one or more loose-storage racks for the loss quantity.
 * Mirrors GrnItemRacksTable but for `lossQty` instead of `qty`.
 */
export const GrnItemLossRacksTable = MainSchema.table('grn_item_loss_racks', {
  id: uuid('id').defaultRandom().notNull().primaryKey(),
  grnItemId: uuid('grn_item_id').notNull(),
  rackId: uuid('rack_id').notNull(),
  quantity: numeric('quantity', { precision: 10, scale: 2 }).notNull().default('0'),
});

export type GrnItemLossRackType = typeof GrnItemLossRacksTable.$inferSelect;
export type GrnItemLossRackInsertType = typeof GrnItemLossRacksTable.$inferInsert;
