CREATE TABLE "main"."drivers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"phone" text NOT NULL,
	"license_number" text NOT NULL,
	"license_expiry" text NOT NULL,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"plate_number" text,
	"vehicle_type" text,
	"fleet_category" text,
	"barcode" text,
	"clocked_in_at" timestamp with time zone,
	"email" varchar(100),
	"password_hash" varchar(255),
	"btm" numeric(12, 2),
	"bdm" numeric(12, 2),
	"payload" numeric(12, 2),
	"length" text,
	"width" text,
	"height" text,
	"pallet_4x3" numeric(6, 2),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);