name: Initialize Repository

on:
  push:
    branches:
      - depricated
      
jobs:
  initialize:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip init]') || github.event.repository.name != 'express-template' }}
    steps:
      - uses: actions/checkout@v4

      - name: Initialize project
        run: |
          node init.js

      - name: Reset version and clear changelog
        run: |
          # Reset version in package.json
          npm version 0.1.0 --no-git-tag-version

          # Clear CHANGELOG.md
          echo '# Changelog\n\nAll notable changes to this project will be documented in this file.\n' > CHANGELOG.md

      - name: Delete existing git tags
        run: |
          tags=$(git tag)
          if [ -n "$tags" ]; then
            git tag -d $(git tag)
            echo "All git tags have been deleted."
          else
            echo "No git tags to delete."
          fi

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add package.json CHANGELOG.md
          git commit -m "Initialize project version and changelog [skip ci]"
          git push origin main